@host = https://api.github.com/graphql
@contentType = application/json
@xRequestType= GraphQL

###

POST {{host}}
Content-Type: {{contentType}}
X-Request-Type: {{xRequestType}}
Authorization: Bearer {{GITHUB_API_KEY}}

query {
  rateLimit {
    remaining
    cost
  }
  user(login: "focuscookie") {
    avatarUrl
    bio
  }
}

### 

POST {{host}}
Content-Type: {{contentType}}
X-Request-Type: {{xRequestType}}
Authorization: Bearer {{GITHUB_API_KEY}}

query {
  user(login: "focuscookie") {
    name
    contributionsCollection {
      contributionCalendar {
        colors
        totalContributions
        weeks {
          contributionDays {
            color
            contributionCount
            date
            weekday
          }
          firstDay
        }
      }
    }
  }
}