POST https://api.github.com/graphql
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Bearer {{GITHUB_API_KEY}}

query {
  rateLimit {
    remaining
    cost
  }
}

### 

GET https://api.github.com/user/FocusCookie/fm-time-tracking-dashboard

###
GET https://api.github.com/repos/FocusCookie/fm-time-tracking-dashboard/deployments

###
GET https://api.github.com/orgs/CodeAcademyBerlin/public_members

###
GET https://api.github.com/orgs/CodeAcademyBerlin/teams