@host = https://api.github.com/graphql

###

POST {{host}}
Content-Type: application/json
X-Request-Type: GraphQL
Authorization: Bearer {{GITHUB_API_KEY}}

query {
  rateLimit {
    remaining
    cost
  }
  user(login: "focuscookie") {
    avatarUrl
    bio
  }
}

### 